version: '3.8'
services:
  test_postgres:
    container_name: test_postgres
    image: postgres:14.4-alpine
    ports:
      - 5433:5432
    env_file: ./.env.test
    networks:
      - test_network
networks:
  test_network:
