name: App CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  DATABASE_URL: postgresql://postgres:@127.0.0.1:5433/test_db

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.4-alpine
        env:
          POSTGRES_DB: test_db
          POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run lint
      - run: npm run test:ci
